version: 2
executorType: docker

containerInfo:
  - image: ruby:2.2.3
    cmd: ["/bin/bash"]

stages:
  build:
    workDir: ~/clojure-by-example

    environment:
      - WORK_DIR: ~/clojure-by-example

    steps:
      - type: shell
        shell: /bin/bash
        pwd: /
        command: apt-get -q update; apt-get -y install libgmp3-dev

      - type: checkout

      - type: shell
        shell: /bin/bash
        command: cp .aspell.en.pws ~/

      - type: cache-restore
        keys:
          - projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - type: shell
        shell: /bin/bash
        command: bundle install --path vendor/bundle

      - type: cache-save
        key: projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
