version: 2
executorType: docker

containerInfo:
  - image: ruby:2.2.3
    cmd: ["/bin/bash"]

stages:
  build:
    workDir: ~/clojure-by-example

    environment:
      - WORK_DIR: ~/clojure-by-example

    steps:
      - type: shell
        shell: /bin/bash
        pwd: /
        command: apt-get -q update; apt-get -y install libgmp3-dev aspell-en

      - type: checkout

      - type: shell
        shell: /bin/bash
        command: cp .aspell.en.pws ~/

      - type: cache-restore
        keys:
          - projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - type: shell
        shell: /bin/bash
        command: bundle install --path vendor/bundle

      - type: cache-save
        key: projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: shell
        shell: /bin/bash
        command: bundle exec rake spellcheck

      - type: deploy
        name: "Deploy to staging"
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git config --global user.email "kimh-machine1@kimh.33mail.com"
            git config --global user.name "kimh-machine1"
            git remote remove origin
            git remote add origin git@github.com:kimh/clojure-by-example.git
            bundle exec rake publish COMMIT_MESSAGE_SUFFIX="[ci skip]"
          fi
