version: 2
executorType: docker

containerInfo:
  - image: ubuntu:14.04
    cmd: ["/bin/bash"]

stages:
  build:
    workDir: ~/$CIRCLE_PROJECT_REPONAME

    steps:
      - type: shell
        shell: /bin/bash
        pwd: /
        command: apt-get -q update; apt-get install -y git-core

      - type: checkout

      - type: shell
        shell: /bin/bash
        command: pwd
