version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.5

    working_directory: /root/clojure-by-example

    steps:
      - checkout

      - run: apt-get -q update; apt-get -y install libgmp3-dev curl

      - restore_cache:
          keys:
            - projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle

  deploy:
    docker:
      - image: ruby:2.3.5

    working_directory: /root/clojure-by-example

    steps:
      - checkout

      - restore_cache:
          keys:
            - projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle

      - run: |
          git config --global user.email "kimh-machine1@kimh.33mail.com"
          git config --global user.name "kimh-machine1"
          git remote remove origin
          git remote add origin git@github.com:kimh/clojure-by-example.git
          bundle exec rake publish commit_message_suffix="[ci skip]"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
