version: 2
workflows:
  version: 2
  deploy-site:
    jobs:
    - whatever: {}
jobs:
  whatever:
    environment:
    - CIRCLE_TEST_REPORTS: test_results
    - CIRCLE_ARTIFACTS: test_results
    docker:
    - image: ruby:2.3.5
    steps:
    - run:
        command: apt-get -q update; apt-get -y install libgmp3-dev
    - checkout
    - run:
        name: Configure bundler
        command: |
          bundle config jobs 3
          bundle config path vendor/bundle
          bundle config retry 3
    - run:
        name: Log versions for debugging
        command: |
          gem --version
          bundle --version
    - restore_cache:
        name: Restore bundler cache
        keys:
        - rails-demo-bundle-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - rails-demo-bundle-{{ arch }}-{{ .Branch }}-
        - rails-demo-bundle-{{ arch }}-{{ Environment.DEFAULT_BRANCH }}-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Clear unused bundle gems before saving cache
        command: bundle clean --force
    - save_cache:
        key: rails-demo-bundle-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
